/*
Gatekeeper API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// VerifyUserResponse struct for VerifyUserResponse
type VerifyUserResponse struct {
	Id string `json:"id"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	// Assessment of whether person will be accepted or not
	Status string `json:"status"`
	Details VerifyUserResponseDetails `json:"details"`
}

// NewVerifyUserResponse instantiates a new VerifyUserResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerifyUserResponse(id string, status string, details VerifyUserResponseDetails) *VerifyUserResponse {
	this := VerifyUserResponse{}
	this.Id = id
	this.Status = status
	this.Details = details
	return &this
}

// NewVerifyUserResponseWithDefaults instantiates a new VerifyUserResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerifyUserResponseWithDefaults() *VerifyUserResponse {
	this := VerifyUserResponse{}
	return &this
}

// GetId returns the Id field value
func (o *VerifyUserResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *VerifyUserResponse) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *VerifyUserResponse) SetId(v string) {
	o.Id = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *VerifyUserResponse) GetCreatedAt() string {
	if o == nil || o.CreatedAt == nil {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifyUserResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *VerifyUserResponse) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *VerifyUserResponse) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *VerifyUserResponse) GetUpdatedAt() string {
	if o == nil || o.UpdatedAt == nil {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifyUserResponse) GetUpdatedAtOk() (*string, bool) {
	if o == nil || o.UpdatedAt == nil {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *VerifyUserResponse) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt != nil {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *VerifyUserResponse) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetStatus returns the Status field value
func (o *VerifyUserResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *VerifyUserResponse) GetStatusOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *VerifyUserResponse) SetStatus(v string) {
	o.Status = v
}

// GetDetails returns the Details field value
func (o *VerifyUserResponse) GetDetails() VerifyUserResponseDetails {
	if o == nil {
		var ret VerifyUserResponseDetails
		return ret
	}

	return o.Details
}

// GetDetailsOk returns a tuple with the Details field value
// and a boolean to check if the value has been set.
func (o *VerifyUserResponse) GetDetailsOk() (*VerifyUserResponseDetails, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Details, true
}

// SetDetails sets field value
func (o *VerifyUserResponse) SetDetails(v VerifyUserResponseDetails) {
	o.Details = v
}

func (o VerifyUserResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if o.CreatedAt != nil {
		toSerialize["created_at"] = o.CreatedAt
	}
	if o.UpdatedAt != nil {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if true {
		toSerialize["status"] = o.Status
	}
	if true {
		toSerialize["details"] = o.Details
	}
	return json.Marshal(toSerialize)
}

type NullableVerifyUserResponse struct {
	value *VerifyUserResponse
	isSet bool
}

func (v NullableVerifyUserResponse) Get() *VerifyUserResponse {
	return v.value
}

func (v *NullableVerifyUserResponse) Set(val *VerifyUserResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifyUserResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifyUserResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifyUserResponse(val *VerifyUserResponse) *NullableVerifyUserResponse {
	return &NullableVerifyUserResponse{value: val, isSet: true}
}

func (v NullableVerifyUserResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifyUserResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


